### ISSUE TITLE
Fatal error: Class '\Perry\Representation\Eve\v1\SovStructureCollection' not found

### ISSUE THREAD

**Issue by RedAces** [3rdpartyeve/perry#8]
Using the new endpoint described by CCP Foxfour here: https://developers.eveonline.com/blog/article/aegis-sovereignty-api-changes leads to this error:

```
Fatal error: Class '\Perry\Representation\Eve\v1\SovStructureCollection' not found in vendor\3rdpartyeve\perry\src\Perry\Perry.php on line 21
```

Seems like the two new end points /sovereignty/structures/ and /sovereignty/campaigns/ aren't supported by Perry yet?

Can I somehow assist in adding them?

Thanks in advance!

**Comment by ppetermann** [comment]
i have a generator that creates those classes, but usually i can't run it before stuff is live, i just did a run, and the class should be there by now.
However CCP has changed a few other things around, so as it looks it might break some of the previously available classes :(
